version: '3.1'
services:
  webserver:
    ports:
    - 8501:8501
  minio:
    image: quay.io/minio/minio:latest
    platform: linux/amd64
    command:
    - server 
    - /data 
    - --console-address 
    - ":9001"
    ports:
    - 9000:9000
    - 9001:9001
    networks:
      - airflow
  weaviate:
    image: semitechnologies/weaviate:latest
    command: "--host 0.0.0.0 --port '8081' --scheme http"
    ports:
    - 8081:8081
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai, backup-s3, qna-openai'
      CLUSTER_HOSTNAME: 'node1'
      BACKUP_S3_BUCKET: 'weaviate-backup'
      BACKUP_S3_ENDPOINT: 'minio:9000'
      BACKUP_S3_USE_SSL: 'false'
      AWS_ACCESS_KEY_ID: 'minioadmin'
      AWS_SECRET_ACCESS_KEY: 'minioadmin'
    networks:
      - airflow
  mlflow:
    image: ghcr.io/mlflow/mlflow
    command:
    - bash 
    - -c
    - '(pip install -q boto3) && (mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////data/mlflow_backend.db --default-artifact-root s3://mlflow-data)'
    ports:
    - 5000:5000
    volumes:
    - ${PWD}/include/mlflow/data:/data
    networks:
      - airflow