name: 'jaffle_shop'

config-version: 2
version: '0.1'

model-paths: ["models"]
# seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    # - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dev:
    materialized: table
      # staging:
      #   materialized: view

# profile: snowflake_conn

# vars:
#   source_schema_name: 'michaelgregory'